/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

import { ColorPaletteTokens, ColorTokens } from "@fluentui/react-components";
import { ColorThemeKind } from "./vscodeWebViewProvider";

export function getCustomColor(themeKind: ColorThemeKind): ColorTokens {
	const customTheme: ColorTokens = {
		colorNeutralForeground1: "var(--vscode-editor-foreground)",
		colorNeutralForeground1Hover: "var(--vscode-tab-activeForeground)",
		colorNeutralForeground1Pressed: "var(--vscode-tab-activeForeground)",
		colorNeutralForeground1Selected: "var(--vscode-tab-activeForeground)",
		colorNeutralForeground2: "var(--vscode-editor-foreground)",
		colorNeutralForeground2Hover: "var(--vscode-tab-activeForeground)",
		colorNeutralForeground2Pressed: "var(--vscode-tab-activeForeground)",
		colorNeutralForeground2Selected: "var(--vscode-tab-activeForeground)",
		colorNeutralForeground2BrandHover: "",
		colorNeutralForeground2BrandPressed: "",
		colorNeutralForeground2BrandSelected: "",
		colorNeutralForeground3: "var(--vscode-editor-foreground)",
		colorNeutralForeground3Hover: "",
		colorNeutralForeground3Pressed: "",
		colorNeutralForeground3Selected: "",
		colorNeutralForeground3BrandHover: "",
		colorNeutralForeground3BrandPressed: "",
		colorNeutralForeground3BrandSelected: "",
		colorNeutralForeground4: "var(--vscode-editor-foreground)",
		colorNeutralForegroundDisabled: "",
		colorNeutralForegroundInvertedDisabled: "",
		colorBrandForegroundLink: "",
		colorBrandForegroundLinkHover: "",
		colorBrandForegroundLinkPressed: "",
		colorBrandForegroundLinkSelected: "",
		colorNeutralForeground2Link: "",
		colorNeutralForeground2LinkHover: "",
		colorNeutralForeground2LinkPressed: "",
		colorNeutralForeground2LinkSelected: "",
		colorCompoundBrandForeground1: "",
		colorCompoundBrandForeground1Hover: "",
		colorCompoundBrandForeground1Pressed: "",
		colorBrandForeground1: "",
		colorBrandForeground2: "",
		colorBrandForeground2Hover: "",
		colorBrandForeground2Pressed: "",
		colorNeutralForeground1Static: "",
		colorNeutralForegroundInverted: "",
		colorNeutralForegroundInvertedHover: "",
		colorNeutralForegroundInvertedPressed: "",
		colorNeutralForegroundInvertedSelected: "",
		colorNeutralForegroundInverted2: "",
		colorNeutralForegroundOnBrand: "",
		colorNeutralForegroundStaticInverted: "",
		colorNeutralForegroundInvertedLink: "",
		colorNeutralForegroundInvertedLinkHover: "",
		colorNeutralForegroundInvertedLinkPressed: "",
		colorNeutralForegroundInvertedLinkSelected: "",
		colorBrandForegroundInverted: "",
		colorBrandForegroundInvertedHover: "",
		colorBrandForegroundInvertedPressed: "",
		colorBrandForegroundOnLight: "",
		colorBrandForegroundOnLightHover: "",
		colorBrandForegroundOnLightPressed: "",
		colorBrandForegroundOnLightSelected: "",
		colorNeutralBackground1: "var(--vscode-editor-background)",
		colorNeutralBackground1Hover: "",
		colorNeutralBackground1Pressed: "",
		colorNeutralBackground1Selected: "",
		colorNeutralBackground2: "var(--vscode-editor-background)",
		colorNeutralBackground2Hover: "",
		colorNeutralBackground2Pressed: "",
		colorNeutralBackground2Selected: "",
		colorNeutralBackground3: "var(--vscode-editor-background)",
		colorNeutralBackground3Hover: "",
		colorNeutralBackground3Pressed: "",
		colorNeutralBackground3Selected: "",
		colorNeutralBackground4: "var(--vscode-editor-background)",
		colorNeutralBackground4Hover: "",
		colorNeutralBackground4Pressed: "",
		colorNeutralBackground4Selected: "",
		colorNeutralBackground5: "var(--vscode-editor-background)",
		colorNeutralBackground5Hover: "",
		colorNeutralBackground5Pressed: "",
		colorNeutralBackground5Selected: "",
		colorNeutralBackground6: "var(--vscode-editor-background)",
		colorNeutralBackgroundInverted: "",
		colorNeutralBackgroundStatic: "",
		colorNeutralBackgroundAlpha: "",
		colorNeutralBackgroundAlpha2: "",
		colorSubtleBackground: "",
		colorSubtleBackgroundHover: "",
		colorSubtleBackgroundPressed: "",
		colorSubtleBackgroundSelected: "",
		colorSubtleBackgroundLightAlphaHover: "",
		colorSubtleBackgroundLightAlphaPressed: "",
		colorSubtleBackgroundLightAlphaSelected: "",
		colorSubtleBackgroundInverted: "",
		colorSubtleBackgroundInvertedHover: "",
		colorSubtleBackgroundInvertedPressed: "",
		colorSubtleBackgroundInvertedSelected: "",
		colorTransparentBackground: "",
		colorTransparentBackgroundHover: "",
		colorTransparentBackgroundPressed: "",
		colorTransparentBackgroundSelected: "",
		colorNeutralBackgroundDisabled: "",
		colorNeutralBackgroundInvertedDisabled: "",
		colorNeutralStencil1: "",
		colorNeutralStencil2: "",
		colorNeutralStencil1Alpha: "",
		colorNeutralStencil2Alpha: "",
		colorBackgroundOverlay: "",
		colorScrollbarOverlay: "",
		colorBrandBackground: (themeKind === ColorThemeKind.HighContrast) ? "var(--vscode-button-border)" : "var(--vscode-button-background)",
		colorBrandBackgroundHover: (themeKind === ColorThemeKind.HighContrast) ? "var(--vscode-button-border)" :"var(--vscode-button-secondaryHoverBackground)",
		colorBrandBackgroundPressed: (themeKind === ColorThemeKind.HighContrast) ? "var(--vscode-button-border)" :"var(--vscode-button-background)",
		colorBrandBackgroundSelected: (themeKind === ColorThemeKind.HighContrast) ? "var(--vscode-button-border)" :"var(--vscode-button-background)",
		colorCompoundBrandBackground: "var(--vscode-button-background)",
		colorCompoundBrandBackgroundHover: "var(--vscode-button-secondaryHoverBackground)",
		colorCompoundBrandBackgroundPressed: "var(--vscode-button-background)",
		colorBrandBackgroundStatic: "",
		colorBrandBackground2: "",
		colorBrandBackground2Hover: "",
		colorBrandBackground2Pressed: "",
		colorBrandBackground3Static: "",
		colorBrandBackground4Static: "",
		colorBrandBackgroundInverted: "",
		colorBrandBackgroundInvertedHover: "",
		colorBrandBackgroundInvertedPressed: "",
		colorBrandBackgroundInvertedSelected: "",
		colorNeutralCardBackground: "",
		colorNeutralCardBackgroundHover: "",
		colorNeutralCardBackgroundPressed: "",
		colorNeutralCardBackgroundSelected: "",
		colorNeutralCardBackgroundDisabled: "",
		colorNeutralStrokeAccessible: "",
		colorNeutralStrokeAccessibleHover: "",
		colorNeutralStrokeAccessiblePressed: "",
		colorNeutralStrokeAccessibleSelected: "",
		colorNeutralStroke1: "",
		colorNeutralStroke1Hover: "",
		colorNeutralStroke1Pressed: "",
		colorNeutralStroke1Selected: "",
		colorNeutralStroke2: "",
		colorNeutralStroke3: "",
		colorNeutralStrokeSubtle: "",
		colorNeutralStrokeOnBrand: "",
		colorNeutralStrokeOnBrand2: "",
		colorNeutralStrokeOnBrand2Hover: "",
		colorNeutralStrokeOnBrand2Pressed: "",
		colorNeutralStrokeOnBrand2Selected: "",
		colorBrandStroke1: "",
		colorBrandStroke2: "",
		colorBrandStroke2Hover: "",
		colorBrandStroke2Pressed: "",
		colorBrandStroke2Contrast: "",
		colorCompoundBrandStroke: (themeKind === ColorThemeKind.HighContrast) ? "var(--vscode-button-border)" : "var(--vscode-button-background)",
		colorCompoundBrandStrokeHover: (themeKind === ColorThemeKind.HighContrast) ? "var(--vscode-button-border)" : "var(--vscode-button-secondaryHoverBackground)",
		colorCompoundBrandStrokePressed: (themeKind === ColorThemeKind.HighContrast) ? "var(--vscode-button-border)" : "var(--vscode-button-background)",
		colorNeutralStrokeDisabled: "",
		colorNeutralStrokeInvertedDisabled: "",
		colorTransparentStroke: "",
		colorTransparentStrokeInteractive: "",
		colorTransparentStrokeDisabled: "",
		colorNeutralStrokeAlpha: "",
		colorNeutralStrokeAlpha2: "",
		colorStrokeFocus1: "",
		colorStrokeFocus2: "",
		colorNeutralShadowAmbient: "",
		colorNeutralShadowKey: "",
		colorNeutralShadowAmbientLighter: "",
		colorNeutralShadowKeyLighter: "",
		colorNeutralShadowAmbientDarker: "",
		colorNeutralShadowKeyDarker: "",
		colorBrandShadowAmbient: "",
		colorBrandShadowKey: "",
	};
	return customTheme;
}

function statusColorPalette(kind: ColorThemeKind): ColorPaletteTokens {
	const colors: ColorPaletteTokens = {

	}
	return colors;
}